env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash
    TOKEN: ENCRYPTED[6d518771e557b56baebb2ede3d91059daa8f1b7750843a0875a5cfc9613595b78879dfafd75d4f058ae3b9927878e1d5]

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - curl -sL https://raw.githubusercontent.com/Hakimi0804/scripts/main/builds/mkpbrp_RMX2151.sh | bash
